// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3s__gzTETpGAYRNUwFbX8Es7jT2zZCY',
    appId: '1:909168844745:android:447d5760a5e63b5a215218',
    messagingSenderId: '909168844745',
    projectId: 'gig-task-manager-sreehar-abe70',
    storageBucket: 'gig-task-manager-sreehar-abe70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZD23QItwtqZmmgq55JbjXCSNHa0kKIw',
    appId: '1:909168844745:ios:b471bc950c03e14c215218',
    messagingSenderId: '909168844745',
    projectId: 'gig-task-manager-sreehar-abe70',
    storageBucket: 'gig-task-manager-sreehar-abe70.firebasestorage.app',
    iosBundleId: 'com.example.gigTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZD23QItwtqZmmgq55JbjXCSNHa0kKIw',
    appId: '1:909168844745:ios:b471bc950c03e14c215218',
    messagingSenderId: '909168844745',
    projectId: 'gig-task-manager-sreehar-abe70',
    storageBucket: 'gig-task-manager-sreehar-abe70.firebasestorage.app',
    iosBundleId: 'com.example.gigTaskManager',
  );
}
